<?php
/**
 * Created by PhpStorm.
 * User: tschet
 * Date: 8/6/15
 * Time: 4:36 PM
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function ndsu_departments_ctools_plugin_api($module, $api) {
    if ($module == 'field_group' && $api == 'field_group') {
        return array('version' => 1);
    }
    if ($module == 'field_validation' && $api == 'default_field_validation_rules') {
        return array('version' => 2);
    }
}